services:
  db: 
    image: mysql:8.0
    container_name: db_fullcycle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - fullcycle-network

  node:
    build:
      context: ./node
    container_name: node_fullcycle
    image: lucasbegnini/fullcycle-node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules # to avoid overwrite node_modules
    networks:
      - fullcycle-network
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    depends_on:
      - db
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}

  nginx:
    build:
      context: ./nginx
    container_name: nginx_fullcycle
    image: lucasbegnini/fullcycle-nginx
    ports:
      - "8080:80"
    networks:
      - fullcycle-network
    depends_on:
      - node

networks:
  fullcycle-network:
    driver: bridge